### ISSUE TITLE
大佬能帮一下我吗

### ISSUE THREAD

**Issue by asdpy2012** [esme518/docker-drpy#1]
我在onrender.com创建好了，打开网址直接到了 进程管理
链接，不用填端口9001。 onrender.com/index 无法打开后台。显示Error responseError code 404.Message: Not Found.
onrender.com：5705/index无法访问此页面。要怎样设置呢？

**Comment by esme518** [comment]
render只支持开放一个端口，并且默认是自动识别的。我为render重新更改了下设计放在render这个分支里了，你到settings里面把Branch修改为render然后重新deploy下，这样onrender.com/index就能进后台了。只是9001的进程管理就别想了，通过开关服务来控制吧，log功能我给调整了你在render的logs可以直接查看。

**Comment by esme518** [comment]
如果还无法使用的话 记得在render的Environment里面添加PORT=5705 这样就能手动指定映射端口了

**Comment by asdpy2012** [comment]
成功了，谢谢你，太感谢了!!!
