### ISSUE TITLE
大佬您好，这个能在宝塔docker中使用吗，应该怎么填，谢谢

### ISSUE THREAD

**Issue by xisohi** [esme518/docker-drpy#2]
![dc](https://user-images.githubusercontent.com/29686769/200304399-b4566eb8-50e9-4957-8721-81343e6154f9.jpg)

**Comment by esme518** [comment]
直接ssh进系统 用命令启动的话会简单方便的多
第一次启动后你可以在宝塔界面里控制启动停止重启之类的
命令参数可以[参考](https://gitcode.net/qq_32394351/dr_py/-/blob/master/%E5%A4%A7%E4%BD%AC%E5%8F%8B%E9%93%BE.md)
```
sudo docker run -d \
  --name drpy \
  --restart=always \
  -p 5705:5705 \
  -p 9001:9001 \
  -e INET_USERNAME=user \
  -e INET_PASSWORD=123 \
  -e AUTOUPDATE=1 \
  esme518/docker-drpy
```
